"""MQTT config file generator.

Produces a JSON5 file at /config/config.json5 (or CONFIG_JSON5_PATH) that
an external MQTT bridge can read. The template uses {{PLACEHOLDER}} markers
so individual values can be swapped via plain string .replace() calls without
any JSON parsing — important since JSON5 is not valid JSON.
"""

import os
from pathlib import Path

from app.core.config_manager import ConfigModel


CONFIG_TEMPLATE = """\
// Generated by HA Energy Dashboard — do not edit manually.
// Re-generated on every settings save when MQTT is fully configured.
{
  mqtt: {
    host: "{{MQTT_HOST}}",
    port: {{MQTT_PORT}},
    user: "{{MQTT_USER}}",
    password: "{{MQTT_PASSWORD}}",
    topic: "{{MQTT_TOPIC}}"
  },
  devices: [
    { entity_id: "{{POWER_ENTITY}}", unit: "W" },
    { entity_id: "{{ENERGY_ENTITY}}", unit: "kWh" }
  ]
}
"""


def generate_config_json5(config: ConfigModel) -> str:
    """Return CONFIG_TEMPLATE with placeholders filled from config."""
    return (
        CONFIG_TEMPLATE
        .replace("{{MQTT_HOST}}", config.mqtt_host or "")
        .replace("{{MQTT_PORT}}", str(config.mqtt_port or 1883))
        .replace("{{MQTT_USER}}", config.mqtt_user or "")
        .replace("{{MQTT_PASSWORD}}", config.mqtt_password or "")
        .replace("{{MQTT_TOPIC}}", config.mqtt_topic or "")
        .replace("{{POWER_ENTITY}}", config.power_entity or "")
        .replace("{{ENERGY_ENTITY}}", config.energy_entity or "")
    )


def write_config_json5(config: ConfigModel) -> None:
    """Write the generated JSON5 to disk.

    Path defaults to /config/config.json5; override via CONFIG_JSON5_PATH
    environment variable (useful in tests and local dev).
    """
    path = Path(
        os.getenv("CONFIG_JSON5_PATH", "/config/config.json5")
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_config_json5(config), encoding="utf-8")
    print(f"[CONFIG] Wrote MQTT config to {path}")
